# Avant de servir la requête, demander à Authelia. 200 : on passe, avec
# l'identité de la personne dans les en-têtes Remote-*. 401 : direction
# le portail de connexion, qui ramène ensuite ici.
auth_request /internal/authelia/authz;

auth_request_set $sas_utilisateur $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;

proxy_set_header Remote-User $sas_utilisateur;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Email $email;
proxy_set_header Remote-Name $name;

auth_request_set $redirection_url $upstream_http_location;
error_page 401 =302 $redirection_url;
